input {
  file {
    path => "/var/log/app/app.jsonl"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {

  json {
    source => "message"

  }

  # Если парсинг не удался — чтобы не спамило, просто дропаем
  if "_jsonparsefailure" in [tags] {
    drop { }
  }

  # Нормализуем timestamp
  if ![timestamp] and [ts] {
    mutate { rename => { "ts" => "timestamp" } }
  }

  # Опционально: убрать исходную строку, чтобы не дублировать
  mutate { remove_field => ["message"] }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }

  # Если хочешь тишину в консоли — закомментируй stdout
  # stdout { codec => rubydebug }
}
