from abc import ABC, abstractmethod
from typing import Protocol, Sequence, Optional, Any
from app.models.models import User, News, Comment


class UserRepo(Protocol):
    def create(self, *, name: str, email: str, verified_author: bool, avatar_url: str | None) -> User: ...
    def get(self, user_id: int) -> Optional[User]: ...
    def list(self, skip: int = 0, limit: int = 100) -> Sequence[User]: ...
    def update(self, user_id: int, **fields) -> Optional[User]: ...
    def delete(self, user_id: int) -> bool: ...

class NewsRepo(Protocol):
    def create(self, *, title: str, content: Any, author_id: int, cover_url: str | None) -> News: ...
    def get(self, news_id: int) -> Optional[News]: ...
    def list(self, skip: int = 0, limit: int = 100) -> Sequence[News]: ...
    def update(self, news_id: int, **fields) -> Optional[News]: ...
    def delete(self, news_id: int) -> bool: ...

class CommentRepo(Protocol):
    def create(self, *, text: str, news_id: int, author_id: int) -> Comment: ...
    def get(self, comment_id: int) -> Optional[Comment]: ...
    def list(self, skip: int = 0, limit: int = 100, *, news_id: int | None = None) -> Sequence[Comment]: ...
    def update(self, comment_id: int, **fields) -> Optional[Comment]: ...
    def delete(self, comment_id: int) -> bool: ...